---
title: "poolCritMargFit2"
author: "jason"
date: "May 23, 2019"
output: html_document
---

```{r setup, include=FALSE}

rm(list = ls())

knitr::opts_chunk$set(echo = TRUE)

#knitr::opts_knit$set(root.dir = "~/GitHub/sourcemem/models/figures/critVarFits")
knitr::opts_knit$set(root.dir = "~/GitHub/sourcemem/models/figures/cDiffusionFits")

library(tidyverse)
```

```{r}
dataset <- read.csv('dataFiltered3.csv')

# Create a new variable to label the subject numbers as strings 
dataset$subjString <- NA

#dataset <- dataset[!(dataset$participant== 1),]
#dataset <- dataset[!(dataset$participant== 13),]
# Get a list of subjects 
data.subjList <- unique(dataset$participant)
#data.subjList <- c(1,2,3,4)

# Custom function to create new variable labels 
create.subj.string <- function(subjNo, dataset){
  
  dataset[dataset$participant==subjNo, 'subjString'] <- sprintf('Subject %d', subjNo)
  
  return(dataset)
}

# Run through loop - don't use lapply or map because subject numbers not in order 
for (sub in 1:length(data.subjList)){
  
  # Get the subject number 
  subjNo <- data.subjList[sub]
  
  # Run function, return data frame (dataset)
  dataset <- create.subj.string(subjNo, dataset)
  
}

# Create as factor for plotting and also include levels so the order is correct 
dataset$subjString <- factor(dataset$subjString, 
                             levels = unique(dataset$subjString))

dataset$participant <- factor(dataset$participant, levels = unique(dataset$participant))


recogdata <- dataset[dataset$recog_rating>3,]
#recogdata$response_error <- abs(recogdata$response_error)

```

```{r}

# The palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```


```{r}

Cont <- read.csv('2020-01-29-18-00_Cont_Marginal_pooled.csv')
Thresh <- read.csv('2020-01-29-18-00_Thresh_Marginal_pooled.csv')
Hybrid <- read.csv('2020-01-29-18-00_Hybrid_Marginal_pooled.csv')

# 
# Cont <- read.csv('2020-01-02_NoCrit_Cont.csv')
# Thresh <- read.csv('2020-01-02_NoCrit_Thresh.csv')
# Hybrid <- read.csv('2020-01-02_NoCrit_Hybrid.csv')


density <- rbind(Cont,Thresh,Hybrid)

#exclude participants 1 and 13, who are non-sig on Rayleigh Test
#density <- density[!(density$participant== 1),]
#density <- density[!(density$participant== 13),]

names(density)[1] <- "model_name"

continuous<- density[density$model_name == 'Cont', ]
threshold<- density[density$model_name == 'Thresh', ]
hybrid<- density[density$model_name == 'Hybrid', ]
```

```{r}
# -------- CONTINUOUS MODEL -------------------
# Initialise columns 
continuous$model <- matrix(NA, dim(continuous)[1])
continuous$theta <- matrix(NA, dim(continuous)[1])

# Find all instances of model, high and theta
continuous$model[which(continuous$is_model == ' true')] <- 1 # model 
continuous$model[which(continuous$is_model == ' false')] <- 0 # not ya model 

continuous$theta[which(continuous$is_theta == ' true')] <- 1 # theta
continuous$theta[which(continuous$is_theta == ' false')] <- 0 # not ya theta 

continuous <- tibble(modelName = continuous$model_name,
                     participant = continuous$participant,
                     model = as.factor(continuous$model),
                     theta = as.factor(continuous$theta),
                     value = continuous$value,
                     prob = continuous$prob)

head(continuous)
# -------- THRESHOLD MODEL -------------------
threshold$model <- matrix(NA, dim(threshold)[1])
threshold$theta <- matrix(NA, dim(threshold)[1])

# Find all instances of model, high and theta
threshold$model[which(threshold$is_model == ' true')] <- 1 # model 
threshold$model[which(threshold$is_model == ' false')] <- 0 # not ya model 

threshold$theta[which(threshold$is_theta == ' true')] <- 1 # theta
threshold$theta[which(threshold$is_theta == ' false')] <- 0 # not ya theta 

threshold <- tibble(modelName = threshold$model_name,
                    participant = threshold$participant,
                    model = as.factor(threshold$model),
                    theta = as.factor(threshold$theta),
                    value = threshold$value,
                    prob = threshold$prob)

# -------- HYBRID MODEL -------------------
hybrid$model <- matrix(NA, dim(hybrid)[1])
hybrid$theta <- matrix(NA, dim(hybrid)[1])

# Find all instances of model, high and theta
hybrid$model[which(hybrid$is_model == ' true')] <- 1 # model 
hybrid$model[which(hybrid$is_model == ' false')] <- 0 # not ya model 

hybrid$theta[which(hybrid$is_theta == ' true')] <- 1 # theta
hybrid$theta[which(hybrid$is_theta == ' false')] <- 0 # not ya theta 

hybrid <- tibble(modelName = hybrid$model_name,
                 participant = hybrid$participant,
                 model = as.factor(hybrid$model),
                 theta = as.factor(hybrid$theta),
                 value = hybrid$value,
                 prob = hybrid$prob)
```

```{r}
# -------- CONTINUOUS MODEL -------------------

# Create a new variable to label the subject numbers as strings 
continuous$subjString <- NA

# Get a list of subjects 
data.subjList <- unique(continuous$participant)
#data.subjList <- c(1,2,3,4)

# Custom function to create new variable labels 
create.subj.string <- function(subjNo, density){
  
  density[density$participant==subjNo, 'subjString'] <- sprintf('Subject %d', subjNo)
  
  return(density)
}

# Run through loop - don't use lapply or map because subject numbers not in order 
for (sub in 1:length(data.subjList)){
  
  # Get the subject number 
  subjNo <- data.subjList[sub]
  
  # Run function, return data frame (density)
  continuous <- create.subj.string(subjNo, continuous)
  
}

# Create as factor for plotting and also include levels so the order is correct 
continuous$subjString <- factor(continuous$subjString, 
                                levels = unique(continuous$subjString))

continuous$participant <- factor(continuous$participant, levels = unique(continuous$participant))

# Get a list of the subject strings you created just to double check 
continuous.subjString <- unique(continuous$subjString)

```

```{r}


# Thetas 
continuous_theta <- continuous[continuous$theta == 1,]


# RTs 
continuous_rt <- continuous[continuous$theta == 0,]

# Model Theta 
m_continuous_theta <- continuous_theta[continuous_theta$model == 1,]

# Data Theta
d_continuous_theta <- continuous_theta[continuous_theta$model == 0,]


# model predicted RT data 
m_continuous_rt<- continuous_rt[continuous_rt$model == 1, ]

# RT data 
d_continuous_rt <- continuous_rt[continuous_rt$model == 0, ]




```

```{r}
# -------- THRESHOLD MODEL -------------------
# Create a new variable to label the subject numbers as strings 
threshold$subjString <- NA

# Get a list of subjects 
data.subjList <- unique(threshold$participant)
#data.subjList <- c(1,2,3,4)

# Custom function to create new variable labels 
create.subj.string <- function(subjNo, density){
  
  density[density$participant==subjNo, 'subjString'] <- sprintf('Subject %d', subjNo)
  
  return(density)
}

# Run through loop - don't use lapply or map because subject numbers not in order 
for (sub in 1:length(data.subjList)){
  
  # Get the subject number 
  subjNo <- data.subjList[sub]
  
  # Run function, return data frame (density)
  threshold <- create.subj.string(subjNo, threshold)
  
}

# Create as factor for plotting and also include levels so the order is correct 
threshold$subjString <- factor(threshold$subjString, 
                               levels = unique(threshold$subjString))

threshold$participant <- factor(threshold$participant, levels = unique(threshold$participant))

# Get a list of the subject strings you created just to double check 
threshold.subjString <- unique(threshold$subjString)

```

```{r}


threshold_theta <- threshold[threshold$theta == 1,]


# RTs 
threshold_rt <- threshold[threshold$theta == 0,]

# Model Theta 
m_threshold_theta <- threshold_theta[threshold_theta$model == 1,]

# Data Theta
d_threshold_theta <- threshold_theta[threshold_theta$model == 0,]


# model predicted RT data 
m_threshold_rt<- threshold_rt[threshold_rt$model == 1, ]

# RT data 
d_threshold_rt <- threshold_rt[threshold_rt$model == 0, ]


```

```{r}
# Create a new variable to label the subject numbers as strings 
hybrid$subjString <- NA

# Get a list of subjects 
data.subjList <- unique(hybrid$participant)
#data.subjList <- c(1,2,3,4)

# Custom function to create new variable labels 
create.subj.string <- function(subjNo, density){
  
  density[density$participant==subjNo, 'subjString'] <- sprintf('Subject %d', subjNo)
  
  return(density)
}

# Run through loop - don't use lapply or map because subject numbers not in order 
for (sub in 1:length(data.subjList)){
  
  # Get the subject number 
  subjNo <- data.subjList[sub]
  
  # Run function, return data frame (density)
  hybrid <- create.subj.string(subjNo, hybrid)
  
}

# Create as factor for plotting and also include levels so the order is correct 
hybrid$subjString <- factor(hybrid$subjString, 
                            levels = unique(hybrid$subjString))

hybrid$participant <- factor(hybrid$participant, levels = unique(hybrid$participant))

# Get a list of the subject strings you created just to double check 
hybrid.subjString <- unique(hybrid$subjString)

```

```{r}

# Thetas 
hybrid_theta <- hybrid[hybrid$theta == 1,]


# RTs 
hybrid_rt <- hybrid[hybrid$theta == 0,]

# Model Theta 
m_hybrid_theta <- hybrid_theta[hybrid_theta$model == 1,]

# Data Theta
d_hybrid_theta <- hybrid_theta[hybrid_theta$model == 0,]


# model predicted RT data 
m_hybrid_rt<- hybrid_rt[hybrid_rt$model == 1, ]

# RT data 
d_hybrid_rt <- hybrid_rt[hybrid_rt$model == 0, ]


model_theta <- rbind(m_continuous_theta,m_threshold_theta,m_hybrid_theta)
model_rt <- rbind(m_continuous_rt,m_threshold_rt,m_hybrid_rt)
```

```{r}
# # The palette with grey:
# cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# 
# # The palette with black:
# cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# 
# # Setup equally spaced colours around wheel 
# gg_color_hue <- function(n) {
#   hues = seq(15, 375, length = n + 1)
#   hcl(h = hues, l = 65, c = 100)[1:n]
# }
# n = 3
# cols = gg_color_hue(n)
cols = c("red","blue","green2")

```

```{r}


plotTheta<-
  # ------ Data ---------------------
# 23/05, substitute data density estimates for histograms
ggplot(data=recogdata,aes(x=recogdata$response_error, ..density..)) + geom_histogram(bins = 50, color="black", fill="white") +
  # ------ Model --------
# Continuous
geom_line(data = model_theta, aes(x = value, prob, colour = factor(modelName)), size = 0.75) +  
  facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 3, scale = "free") + 
  xlab("Response Error (radians)") + 
  
  #Misc
  scale_colour_manual(name="Models",values=cols) +
  
  scale_x_continuous(name ="Response Error (radians)", # also x axis name 
                     breaks = c(-2, 0, 2),
                     labels = c(expression(-pi), "0", expression(pi))) + 
  ylab("Probability \n Density") + 
  ggtitle("Response Error by Subject") +   
  theme(
    # x axis label
    # Theme asthetics to make the plot look nicer 
    axis.text.x = element_text(size=10),  # size of text on the x axis 
    axis.text.y = element_text(size=10),  # size of text on the y axis 
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic"), # caption settings 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black")
  )

```

```{r}


plotRT<-
  # ------ Data ---------------------
# 23/05, substitute data density estimates for histograms
ggplot(data=recogdata,aes(x=recogdata$response_RT, ..density..)) + geom_histogram(bins = 50, color = "black", fill = "white") +
  # ------ Model --------
geom_line(data = model_rt, aes(x = value, prob, colour = factor(modelName)), size = 0.75) +  
  facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 3, scale = "free") + 

  #Misc
  scale_colour_manual(name="Models",values=cols) +
  xlab("Response Time (seconds)") +
  ylab("Probability \n Density") +
  ggtitle("Response Time by Subject") +
  theme(
    # x axis label
    # Theme asthetics to make the plot look nicer
    legend.background = element_blank(),
    axis.text.x = element_text(size=10),  # size of text on the x axis
    axis.text.y = element_text(size=10),  # size of text on the y axis
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5, size = 13), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic", size = 10), # caption settings
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "black")
  )

```

# Theta data
```{r}
# # -------- Response Error -------------------
# plotTheta<-
# # ------ Data ---------------------
# # 23/05, substitute data density estimates for histograms
# ggplot(data=recogdata,aes(x=recogdata$response_error, ..density..)) + geom_histogram(bins = 50, color="black", fill="white") +
#   # ------ Model --------
#   # Continuous
# geom_line(data = m_continuous_theta, aes(x = value, prob), size = 0.75, color = "red") +  
#   facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 3, scale = "free") + 
#   xlab("Response Error (radians)") + 
#   
#   # Threshold
#   geom_line(data = m_threshold_theta, aes(x = value, prob), size = 0.75, color = "blue") +  
#   facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 3, scale = "free") + 
#   xlab("Response Error (radians)") +
#   
#   #Hybrid
#   geom_line(data = m_hybrid_theta, aes(x = value, prob), size = 0.75, color = "green2") +  
#   facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 3, scale = "free") + 
#   xlab("Response Error (radians)") +
#   
#   #Misc
#   scale_colour_manual(name="Models",values=cols) +
#   
#   scale_x_continuous(name ="Response Error (radians)", # also x axis name 
#                      breaks = c(-2, 0, 2),
#                      labels = c(expression(-pi), "0", expression(pi))) + 
#   ylab("Probability \n Density") + 
#   ggtitle("Response Error by Subject") +   
#   theme(
#     # x axis label
#     # Theme asthetics to make the plot look nicer 
#     axis.text.x = element_text(size=10),  # size of text on the x axis 
#     axis.text.y = element_text(size=10),  # size of text on the y axis 
#     plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
#     plot.subtitle = element_text(hjust = 0.5), # subtitle settiings (note, centering requires h = 0.5)
#     plot.caption = element_text(hjust = 0, face = "italic"), # caption settings 
#     panel.grid.major = element_blank(), 
#     panel.grid.minor = element_blank(),
#     panel.background = element_blank(), 
#     axis.line = element_line(colour = "black")
#   )
```

```{r}
# 
# # -------- Response Time -------------------
# plotRT<-
# # ------ Data ---------------------
# ggplot(data=recogdata,aes(x=recogdata$response_RT, ..density..)) + geom_histogram(bins = 50, color = "black", fill = "white") +
#   # ------ Model --------
#   #Continuous
# geom_line(data = m_continuous_rt, aes(x = value, prob), size = 0.75, color = "red") +  
# facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 3, scale = "free") +
#   
#   #Threshold
# geom_line(data = m_threshold_rt, aes(x = value, prob), size = 0.75, color = "blue") +  
# facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 3, scale = "free") +
#   #Hybrid
# geom_line(data = m_hybrid_rt, aes(x = value, prob), size = 0.75, color = "green2") +  
# facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 3, scale = "free") +
#   #Misc
#   xlab("Response Time (seconds)") + 
#   ylab("Probability \n Density") + 
#   ggtitle("Response Time by Subject") +   
#   theme(
#     # x axis label
#     # Theme asthetics to make the plot look nicer 
#     legend.background = element_blank(),
#     axis.text.x = element_text(size=10),  # size of text on the x axis 
#     axis.text.y = element_text(size=10),  # size of text on the y axis 
#     plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
#     plot.subtitle = element_text(hjust = 0.5, size = 13), # subtitle settiings (note, centering requires h = 0.5)
#     plot.caption = element_text(hjust = 0, face = "italic", size = 10), # caption settings 
#     panel.grid.major = element_blank(), 
#     panel.grid.minor = element_blank(),
#     panel.background = element_blank(), 
#     axis.line = element_line(colour = "black")
#   )

```

```{r}
plotTheta
plotRT
```