---
title: "Real_QxQ"
author: "jason"
date: "April 8, 2019"
output: pdf_document
---

```{r setup, include=FALSE}

rm(list = ls())
# knitr::opts_chunk$set(echo = TRUE)

library("ggplot2")
library("plyr")
library("tidyverse")
```

```{r}
setwd("~/GitHub/sourcemem/models/code/gvm/UoMFitPrograms/QQPlots")
#dataset <- read.csv('GVM_High.csv', sep = ",") #.1, .3, .5, .7, .9 quantiles
dataset <- read.csv('Thresh_3quant.csv', sep = ",") #.1, .5, .9 quantiles
#dataset <- read.csv('GVM_high_3quant2.csv', sep = ",") #.3, .5, .7 quantiles

dataset$quantile_idx <- as.factor(dataset$quantile_idx)

```

```{r}

# Create a new variable to label the subject numbers as strings 
dataset$subjString <- NA
# Get a list of subjects 
data.subjList <- unique(dataset$participant)

# Custom function to create new variable labels 
create.subj.string <- function(n, dataset){
  dataset[dataset$participant==n, 'subjString'] <- sprintf("Subject %d", n)
  return(dataset)
}

# Run through loop - don't use lapply or map because subject numbers not in order 
for (sub in 1:length(data.subjList)){
  
  # Get the subject number 
  subjNo <- data.subjList[sub]
  
  # Run function, return data frame (dataset)
  dataset <- create.subj.string(subjNo, dataset)
  
}

# Create as factor for plotting and also include levels so the order is correct 
dataset$subjString <- factor(dataset$subjString, 
                                levels = unique(dataset$subjString))

# Get a list of the subject strings you created just to double check 
data.subjString <- unique(dataset$subjString)


```

```{r}

#Here, I am trying to cut off the model beyond where there furthest x-axis response error quantiles are. Philip does something similar so the model doesn't look like its just totally missing. Doesn't seem to work though, STOP 8/4/19


#participants<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20)
#for (i in participants){
#dataset_b<- dataset[abs(dataset[(dataset$participant == i) & (dataset$is_model == ' true'),]$theta) < max(abs(dataset[(dataset$participant == i)&(dataset$is_model== ' false'),]$theta)),]
#} 

dataset_b <- dataset

data_low <- dataset_b[(dataset_b$is_model==' false') & (dataset_b$is_high==' false'),]

model_low <- dataset_b[(dataset_b$is_model==' true') & (dataset_b$is_high==' false'),]

data_high <- dataset_b[(dataset_b$is_model==' false') & (dataset_b$is_high==' true'),]

model_high <- dataset_b[(dataset_b$is_model==' true') & (dataset_b$is_high==' true'),]


```



```{r}

# The palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Setup equally spaced colours around wheel 
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
n = 3
cols = gg_color_hue(n)


```

High Imaginability 
```{r}

# ---------- Plot Model Predictions ----------------------
# Plot the model predictions as POINTS and LINES 
High_QxQ <- ggplot(data = model_high, 
                   aes(x = model_high$theta, 
                       y = model_high$rt, 
                       group = model_high$quantile_idx,  # group points according to quantiles 
                       colour = quantile_idx)) + 
  geom_line(linemitre = 4) + #geom_point() + 
  # ------------ Plot Data ---------------------------------
# Plot data as POINTS ONLY
geom_point(data = data_high, 
           aes(x = data_high$theta, 
               y = data_high$rt, 
               group = data_high$quantile_idx, 
               colour = quantile_idx)) + 
  # ------------ Group plot by participant -----------------
facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 4, scale = "free") + 
  # ------------ Change some axes settings  ----------------
#scale_y_continuous(limits=c(0, 3)) + 
  scale_x_continuous(name ="Response Error (degrees)", # also x axis name 
                     breaks = c(-2, 0, 2),
                     labels = c(expression(-pi), "0", expression(pi))) + 
  xlab("Response Error (degrees)") + # just in case remove scale x continuous 
  ylab("Response Time (s)") + 
  scale_color_manual(name = "Predicted \nQuantiles",
                     values = cols,  # cbPalette[c(1,2,3)], 
                     labels = c("0.1", "0.5", "0.9")) + 
  # ------------ Change Theme Settings  ----------------
ggtitle("Response Time Quantiles by Error \n High Imageability Condition") + 
  theme(
    
    # Legend settings 
    #legend.justification = c(1, 1), legend.position = c(0.90, 1.09),
    legend.background = element_blank(),
    
    # Axis settingd 
    axis.text.x = element_text(size=7),  # size of text on the x axis 
    axis.text.y = element_text(size=7),  # size of text on the y axis 
    
    # Plot title settings 
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic"), # caption settings 
    
    # Get rid of background panel grid 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black"))

High_QxQ # display the plot 

# Note: Device to use. Can be either be a device function (e.g. png()), 
# or one of "eps", "ps", "tex" (pictex), "pdf", "jpeg", "tiff", "png", 
# "bmp", "svg" or "wmf" (windows only).
#ggsave('HighQQ', plot = High_QxQ, device = "eps", path = NULL,
       #width = 20, height = 20, 
       #scale = 1, dpi = 800, limitsize = TRUE) # 

```


```{r}
# ---------- Plot Model Predictions ----------------------
# Plot the model predictions as POINTS and LINES 
Low_QxQ <- ggplot(data = model_low, 
                   aes(x = model_low$theta, 
                       y = model_low$rt, 
                       group = model_low$quantile_idx,  # group points according to quantiles 
                       colour = quantile_idx)) + 
  geom_line(linemitre = 4) + #geom_point() + 
  # ------------ Plot Data ---------------------------------
# Plot data as POINTS ONLY
geom_point(data = data_low, 
           aes(x = data_low$theta, 
               y = data_low$rt, 
               group = data_low$quantile_idx, 
               colour = quantile_idx)) + 
  # ------------ Group plot by participant -----------------
facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 4, scale = "free") + 
  # ------------ Change some axes settings  ----------------
#scale_y_continuous(limits=c(0, 3)) + 
  scale_x_continuous(name ="Response Error (degrees)", # also x axis name 
                     breaks = c(-2, 0, 2),
                     labels = c(expression(-pi), "0", expression(pi))) + 
  xlab("Response Error (degrees)") + # just in case remove scale x continuous 
  ylab("Response Time (s)") + 
  scale_color_manual(name = "Predicted \nQuantiles",
                     values = cols,  # cbPalette[c(1,2,3)], 
                     labels = c("0.1", "0.5", "0.9")) + 
  # ------------ Change Theme Settings  ----------------
ggtitle("Response Time Quantiles by Error \n Low Imageability Condition") + 
  theme(
    
    # Legend settings 
    #legend.justification = c(1, 1), legend.position = c(0.90, 1.09),
    legend.background = element_blank(),
    
    # Axis settingd 
    axis.text.x = element_text(size=7),  # size of text on the x axis 
    axis.text.y = element_text(size=7),  # size of text on the y axis 
    
    # Plot title settings 
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic"), # caption settings 
    
    # Get rid of background panel grid 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black"))

Low_QxQ # display the plot 

# Note: Device to use. Can be either be a device function (e.g. png()), 
# or one of "eps", "ps", "tex" (pictex), "pdf", "jpeg", "tiff", "png", 
# "bmp", "svg" or "wmf" (windows only).
ggsave('LowQQ', plot = Low_QxQ, device = "eps", path = NULL,
       width = 20, height = 20, 
       scale = 1, dpi = 800, limitsize = TRUE) # 
```