---
title: "QPP_Image"
author: "jason"
date: "August 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
library(ggplot2)
library(circular)

setwd('C:/Users/jason/Documents/2018/Experiment 1/Analysis/R/image-analysis')

dataset <- read.csv("dataset.csv", na.strings = " NA")
dataset <- dataset[,-1] #removes the first variable, which are these weird row labels
dataset[,3] <- as.numeric(factor(dataset$condition, levels=c(' LOW', ' HIGH')))
dataset$recog_rating <- as.factor(dataset$recog_rating) #Confidence Ratings are Discrete



# Set up all the different dataset subsets

#Group Level
# No Recognition Foils 
dataset.no.na <- dataset[dataset$type!=' FOIL', ]
dataset.na <- dataset[dataset$type==' FOIL', ]

# Let's get rid of very slow responses
dataset.no.na <- dataset.no.na[dataset.no.na$response_RT < 4,]

dataset.6conf <- dataset.no.na[dataset.no.na$recog_rating==6,]

# Stimulus only, conditioned on imageability+concreteness ratings
dataset.low <- dataset.no.na[dataset.no.na$condition == 1, ]
dataset.high <- dataset.no.na[dataset.no.na$condition == 2, ]

participants = c("1","2","3","4","5","6","7","8","9","10","11","12","13","15","16","17","18","19","20") 



```

```{r echo=FALSE}


#I want the break points, figuring out the quantiles for absolute error
right.bin.edges <- quantile(abs(dataset.no.na$response_error), 
                            probs=c(0.1, 0.3, 0.5, 0.7, 0.9, 1.0))
left.bin.edges <- c(0.0, right.bin.edges[1:(length(right.bin.edges)-1)])
n.bins <- length(right.bin.edges)

RTQ <- data.frame(matrix(ncol=0,nrow=0))
#Within those quantile bins, work out the RT quantiles
for(i in 1:n.bins) {
  this.min <- left.bin.edges[i]
  this.max <- right.bin.edges[i]
  this.subset <- dataset.no.na[(dataset.no.na$response_error >= this.min) & (dataset.no.na$response_error < this.max), ]
   this.RTQuantile<- quantile(this.subset$response_RT, 
                            probs=c(0.1, 0.3, 0.5, 0.7, 0.9, 1.0))
   RTQ <- rbind(RTQ,this.RTQuantile)
  #data.subset <- rbind(data.subset,this.subset)
}



#Plot
All.Q <- data.frame(matrix(ncol=4,nrow=36))
All.Q[,1] <- rep(c(1:6),each = 6)
All.Q[,2] <- rep(right.bin.edges,each = 6)
All.Q[,3] <- c(1,2,3,4,5,6)

#Had a bit of difficulty getting the third column (Actual RTs) in- this is my shoddy workaround
RTtrans <- t(RTQ)
All.Q[,4] <- c(RTtrans)

colnames(All.Q) <- c("Error_Quantile","Error_bin","RT_Quantile","RT")

allQPP <- ggplot(data = All.Q,aes(x=All.Q$Error_bin, y=All.Q$RT, group=All.Q$RT_Quantile)) + geom_point() #had to set a limit because there are some real big outliers on RT
```

```{r echo=FALSE}
#Same thing, but for high confidence
Hright.bin.edges <- quantile(abs(dataset.6conf$response_error), 
                            probs=c(0.1, 0.3, 0.5, 0.7, 0.9, 1.0))
Hleft.bin.edges <- c(0.0, Hright.bin.edges[1:(length(Hright.bin.edges)-1)])
n.bins <- length(Hright.bin.edges)

HRTQ <- data.frame(matrix(ncol=0,nrow=0))
#Within those quantile bins, work out the RT quantiles
for(i in 1:n.bins) {
  this.min <- Hleft.bin.edges[i]
  this.max <- Hright.bin.edges[i]
  this.subset <- dataset.6conf[(dataset.6conf$response_error >= this.min) & (dataset.6conf$response_error < this.max), ]
   this.RTQuantile<- quantile(this.subset$response_RT, 
                            probs=c(0.1, 0.3, 0.5, 0.7, 0.9, 1.0))
   HRTQ <- rbind(HRTQ,this.RTQuantile)
  #data.subset <- rbind(data.subset,this.subset)
}



#Plot
HighConf.Q <- data.frame(matrix(ncol=4,nrow=36))
HighConf.Q[,1] <- rep(c(1:6),each = 6)
HighConf.Q[,2] <- rep(right.bin.edges,each = 6)
HighConf.Q[,3] <- c(1,2,3,4,5,6)

#Had a bit of difficulty getting the third column (Actual RTs) in- this is my shoddy workaround
HRTtrans <- t(HRTQ)
HighConf.Q[,4] <- c(HRTtrans)

colnames(HighConf.Q) <- c("Error_Quantile","Error_bin","RT_Quantile","RT")

HighConfQPP <- ggplot(data = HighConf.Q,aes(x=HighConf.Q$Error_bin, y=HighConf.Q$RT, group=HighConf.Q$RT_Quantile)) + geom_point() #had to set a limit because there are some real big outliers on RT
```

```{r echo=FALSE}
allQPP
ggsave("allQPP.jpeg", plot = allQPP)
HighConfQPP
ggsave("HighConf.jpeg", plot = HighConfQPP)

```

```{r echo=FALSE}
#Individual Level

participants = c("p1","p2","p3","p4","p5","p6","p7","p8","p9","p10","p11","p12","p13","p15","p16","p17","p18","p19","p20") 

#Individual Level
#participants = c("1","2","3","4","5","6","7","8","9","10","11","12","13","15","16","17","18","19","20")
#sessions = c("1","2","3","4")
#for (i in participants){
#sprintf("dataset.%s",i) <- sprintf("dataset.no.na[dataset.no.na$participant==%s]",i)
#  }

dataset.p1 <- dataset.no.na[dataset.no.na$participant=='1', ]
dataset.p2 <- dataset.no.na[dataset.no.na$participant=='2', ]
dataset.p3 <- dataset.no.na[dataset.no.na$participant=='3', ]
dataset.p4 <- dataset.no.na[dataset.no.na$participant=='4', ]
dataset.p5 <- dataset.no.na[dataset.no.na$participant=='5', ]
dataset.p6 <- dataset.no.na[dataset.no.na$participant=='6', ]
dataset.p7 <- dataset.no.na[dataset.no.na$participant=='7', ]
dataset.p8 <- dataset.no.na[dataset.no.na$participant=='8', ]
dataset.p9 <- dataset.no.na[dataset.no.na$participant=='9', ]
dataset.p10 <- dataset.no.na[dataset.no.na$participant=='10', ]
dataset.p11 <- dataset.no.na[dataset.no.na$participant=='11', ]
dataset.p12 <- dataset.no.na[dataset.no.na$participant=='12', ]
dataset.p13 <- dataset.no.na[dataset.no.na$participant=='13', ]
dataset.p15 <- dataset.no.na[dataset.no.na$participant=='15', ]
dataset.p16 <- dataset.no.na[dataset.no.na$participant=='16', ]
dataset.p17 <- dataset.no.na[dataset.no.na$participant=='17', ]
dataset.p18 <- dataset.no.na[dataset.no.na$participant=='18', ]
dataset.p19 <- dataset.no.na[dataset.no.na$participant=='19', ]
dataset.p20 <- dataset.no.na[dataset.no.na$participant=='20', ]

participants = c("p1","p2","p3","p4","p5","p6","p7","p8","p9","p10","p11","p12","p13","p15","p16","p17","p18","p19","p20") 

for (i in participants){
part <- data.frame()
  }

```