---
title: "ConcSession2"
author: "Jason Zhou"
date: "5 July 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```



```{r}
setwd('C:/Users/jason/Documents/GitHub/sourcemem/analysis/data/')
dataset <- data.frame()

participants = c("p1","p2","p3","p4","p4","p5","p6","p7","p8","p9","p10","p11","p12","p13","p15","p16","p17","p18","p19","p20") 

#participants = c("p1","p2","p3","p4","p4","p5","p6","p7","p8","p9","p10","p11","p12",
                 #"p13","p14","p15","p16","p17","p18","p19","p20") #c is vector, list is v general
for (i in participants){
  participant_dataset <- data.frame()
  for (j in 1:4){
    sessions = c("1","2","3","4")
    s <- j
    this_session_dataset <- read.csv(paste(i,"_",j,".csv",sep=""))
    this_session_dataset$session <- j
    this_session_dataset$session <- as.factor(this_session_dataset$session)
    participant_dataset <- rbind(participant_dataset,this_session_dataset)
    
    participant_dataset <- participant_dataset[participant_dataset$type!=' FOIL', ]
    
    
    participant_dataset$response_RT <- as.numeric(as.vector(participant_dataset$response_RT))
        participant_dataset$response_angle<- as.numeric(as.vector(participant_dataset$response_angle))
    
  }
#--- FILTERING SLOW RESPONSES ---#

  # 1.Filter out responses slower than 5 seconds
  participant_dataset <- participant_dataset[!(participant_dataset$response_RT>5),]
  
  # 2.Filter out responses slower than three standard deviations above median RT for each participant
  participant_dataset<-participant_dataset[!(participant_dataset$response_RT>(3*(sd(participant_dataset$response_RT)) + median(participant_dataset$response_RT,na.rm=TRUE))), ]
#---------------------------------
  
  participant_dataset$participant <- i
  
  name <- paste(i,"data",sep="_")
  assign(name,participant_dataset)
  dataset <- rbind(dataset,participant_dataset) #could have done this with lists, but because its all the same, we are doing it with one big dataset, added a new variable that identifies.
}


#Cleaning up the dataset

dataset <- dataset[,-1] #removes the first variable, which are these weird row labels
dataset <- dataset[,-1] #removes STIM/FOIL label


#Recoding Participant 
dataset$participant[dataset$participant=="p1"]<-1
dataset$participant[dataset$participant=="p2"]<-2
dataset$participant[dataset$participant=="p3"]<-3
dataset$participant[dataset$participant=="p4"]<-4
dataset$participant[dataset$participant=="p5"]<-5
dataset$participant[dataset$participant=="p6"]<-6
dataset$participant[dataset$participant=="p7"]<-7
dataset$participant[dataset$participant=="p8"]<-8
dataset$participant[dataset$participant=="p9"]<-9
dataset$participant[dataset$participant=="p10"]<-10
dataset$participant[dataset$participant=="p11"]<-11
dataset$participant[dataset$participant=="p12"]<-12
dataset$participant[dataset$participant=="p13"]<-13
dataset$participant[dataset$participant=="p15"]<-15
dataset$participant[dataset$participant=="p16"]<-16
dataset$participant[dataset$participant=="p17"]<-17
dataset$participant[dataset$participant=="p18"]<-18
dataset$participant[dataset$participant=="p19"]<-19
dataset$participant[dataset$participant=="p20"]<-20

#Recoding Low/High
dataset$condition <- relevel(dataset$condition," LOW")
dataset$condition <- as.numeric(factor(dataset$condition))
#dataset$recog_rating <- as.factor(dataset$recog_rating) #Confidence Ratings are Discrete


dataset$response_error <- as.numeric(as.character(dataset$response_error))
dataset.no.na <- dataset[dataset$type!=' FOIL', ]
dataset.na <- dataset[dataset$type==' FOIL', ]

recog <- dataset.no.na[dataset$recog_rating > 3, ]
unrecog <- dataset.no.na[dataset$recog_rating <= 3, ]
high <- dataset.no.na[dataset$recog_rating == 6, ]


allHist<- ggplot(data = dataset.no.na, aes(x = dataset.no.na$response_error)) + geom_histogram(bins = 100) + scale_y_continuous(limits=c(0, 700)) + labs(title ="All Recognition Ratings", x = "Response Error (radians)", y = "Frequency") + theme_classic()

unrecogHist<- ggplot(data = unrecog, aes(x = unrecog$response_error)) + geom_histogram(bins = 100) + scale_y_continuous(limits=c(0, 700)) + labs(title ="Unrecognized Items", x = "Response Error (radians)", y = "Frequency") + theme_classic()


recogHist<- ggplot(data = recog, aes(x = recog$response_error)) + geom_histogram(bins = 100) + scale_y_continuous(limits=c(0, 700)) + labs(title ="Recognized Items", x = "Response Error (radians)", y = "Frequency") + theme_classic()

highHist<- ggplot(data = high, aes(x = high$response_error)) + geom_histogram(bins = 100)+ scale_y_continuous(limits=c(0, 700)) + labs(title ="Highlt Recognized Items", x = "Response Error (radians)", y = "Frequency") + theme_classic()

jumboHist <- ggplot() + geom_histogram(data = dataset.no.na, aes(x = dataset.no.na$response_error, fill="All"), bins = 100) + geom_histogram(data = recog, aes(x = recog$response_error, fill="Recognized"), bins = 100) + geom_histogram(data = unrecog, aes(x = unrecog$response_error, fill="Unrecognized"), bins = 100) + theme_classic()+ labs(x = "Response Error (radians)", y = "Frequency",fill = "Recognition Rating")
# Write CSV in R
#write.csv(dataset, file = "dataFiltered3.csv")

```
```{r}

p10_data <- p10_data[(p10_data$recog_rating > 3),]
p10_data$recog_rating <- as.factor(p10_data$recog_rating)

p10_data$responsebin <- "Fast"
p10_data[(p10_data$response_RT > 2.3),]$responsebin <- "Slow"
p10_data$response_error <- as.numeric(as.character(p10_data$response_error))
  
  

cols = c("red","blue","green2","green")

```
```{r}
plotTheta_RT<- ggplot(data=p10_data,aes(x=response_error)) + geom_histogram(bins = 50, color="black", fill="white") + 
  facet_wrap(~responsebin, labeller = label_wrap_gen(width = 30), ncol = 4) +
  xlab("Response Error") +
  ylab("Count") +
  ggtitle("Response Error by RT Category, Participant 10") +
  theme(
    # x axis label
    # Theme asthetics to make the plot look nicer
    legend.background = element_blank(),
    axis.text.x = element_text(size=10),  # size of text on the x axis
    axis.text.y = element_text(size=10),  # size of text on the y axis
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5, size = 13), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic", size = 10), # caption settings
        panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black")
  )

```


```{r}
plotRT_session<- ggplot() + geom_histogram(data=p10_data,aes(x=response_RT, fill = session), color = "black", bins = 50) +  
  facet_wrap(~session, labeller = label_wrap_gen(width = 30), ncol = 4) + 
  xlab("Response Time (seconds)") +
  ylab("Count") +
  ggtitle("Response Time by Session, Participant 10") +
  theme(
    # x axis label
    # Theme asthetics to make the plot look nicer
    legend.background = element_blank(),
    axis.text.x = element_text(size=10),  # size of text on the x axis
    axis.text.y = element_text(size=10),  # size of text on the y axis
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5, size = 13), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic", size = 10), # caption settings
    axis.line = element_line(colour = "black")
  )

# Recognition Ratings
plotRT_conf<- ggplot() + geom_histogram(data=p10_data,aes(x=response_RT, fill = recog_rating), color = "black", bins = 50) +  
  facet_wrap(~recog_rating, labeller = label_wrap_gen(width = 30), ncol = 4) + 
  xlab("Response Time (seconds)") +
  ylab("Count") +
  ggtitle("Response Time by Session, Participant 10") +
  theme(
    # x axis label
    # Theme asthetics to make the plot look nicer
    legend.background = element_blank(),
    axis.text.x = element_text(size=10),  # size of text on the x axis
    axis.text.y = element_text(size=10),  # size of text on the y axis
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5, size = 13), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic", size = 10), # caption settings
    axis.line = element_line(colour = "black")
  )

# Response Error bin



plotRT<- ggplot() + geom_histogram(data=p10_data,aes(x=response_RT), color = "black", fill = "white",bins = 50) +
  xlab("Response Time (seconds)") +
  ylab("Count") +
  ggtitle("Response Time, Participant 10") +
  theme(
    # x axis label
    # Theme asthetics to make the plot look nicer
    legend.background = element_blank(),
    axis.text.x = element_text(size=10),  # size of text on the x axis
    axis.text.y = element_text(size=10),  # size of text on the y axis
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5, size = 13), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic", size = 10), # caption settings
    axis.line = element_line(colour = "black")
  )
```

```{r}



```