---
title: "Real_QxQ"
author: "jason"
date: "April 8, 2019"
output: pdf_document
---

```{r setup, include=FALSE}

rm(list = ls())
# knitr::opts_chunk$set(echo = TRUE)

library("ggplot2")
library("plyr")
library("tidyverse")
library(readr)
knitr::opts_knit$set(root.dir = "~/GitHub/sourcemem/EXPIMG/models/figures/cDiffusionFits")
```

```{r}
data <- read.csv("DataQuantiles.csv")
cont <- read.csv("2020_02_10_19_28_pooled_cont4q.csv")
thresh <- read.csv("2020_02_10_19_28_pooled_thresh4q.csv") 
hybrid <- read.csv("2020_02_10_19_28_pooled_hybrid4q.csv")

dataset <- rbind(data,cont,thresh,hybrid)
dataset$quantile_idx <- as.factor(dataset$quantile_idx)

```

```{r}

# Create a new variable to label the subject numbers as strings 
dataset$subjString <- NA
# Get a list of subjects 
data.subjList <- unique(dataset$participant)

# Custom function to create new variable labels 
create.subj.string <- function(n, dataset){
  dataset[dataset$participant==n, 'subjString'] <- sprintf("Subject %d", n)
  return(dataset)
}

# Run through loop - don't use lapply or map because subject numbers not in order 
for (sub in 1:length(data.subjList)){
  
  # Get the subject number 
  subjNo <- data.subjList[sub]
  
  # Run function, return data frame (dataset)
  dataset <- create.subj.string(subjNo, dataset)
  
}

# Create as factor for plotting and also include levels so the order is correct 
dataset$subjString <- factor(dataset$subjString, 
                                levels = unique(dataset$subjString))

# Get a list of the subject strings you created just to double check 
data.subjString <- unique(dataset$subjString)


```

```{r}

#Custom function to subset model predictions within the minimum and maximum bin of response

 truncate.model <-function(dataset){
   res <- data.frame()
   participants <- unique(dataset$participant)
   for(p in participants) {
     min.error <- min(dataset[(dataset$participant == p) &
                                (dataset$is_model == " false"), 'theta'])
     max.error <- max(dataset[(dataset$participant == p) &
                                (dataset$is_model == " false"), 'theta'])
     res <- rbind(res,
                  dataset[(dataset$participant == p) &
                            (dataset$is_model == " false"), ])
     res <- rbind(res,
                  dataset[(dataset$participant == p) &
                            (dataset$is_model == " true") &
                            (dataset$theta < max.error + 0.2) &
                            (dataset$theta >= 0), ])
   }
   res
 }

dataset_b <- truncate.model(dataset)
```

```{r}

data <- dataset_b[(dataset_b$is_model==' false'),]

model <- dataset_b[(dataset_b$is_model==' true'),]
# Make Absolute
model <- model[model$theta>=0,]

# Continuous
cont <- model[model$model_name == 'Continuous',]

# Threshold
thresh <- model[model$model_name == 'Threshold',]

# Continuous
hybrid <- model[model$model_name == 'Hybrid',]
```



```{r}

# # The palette with grey:
# cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# 
# # The palette with black:
# cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# 
# # Setup equally spaced colours around wheel 
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
n = 3
cols = gg_color_hue(n)


```

```{r}
# #Plot data only
# 
# DataQxQ <- ggplot(data = data, 
#            aes(x = data$theta, 
#                y = data$rt, 
#                group = data$quantile_idx, 
#                colour = quantile_idx)) + geom_point() +
#           geom_line
#   # ------------ Group plot by participant -----------------
# facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 4, scale = "free")
#   # ------------ Change some axes settings  ----------------

```


```{r}

# ---------- Plot Model Predictions ----------------------
# Plot the model predictions as POINTS and LINES 
QxQ <- ggplot(data = data, 
            aes(x = data$theta, 
                y = data$rt, 
                group = data$quantile_idx, 
                colour = quantile_idx)) + geom_point() +
  
# Plot continuous model           
 geom_line(data = model,
            aes(x = model$theta,
                y = model$rt,
                group=interaction(model$quantile_idx, model$model_name), 
                linetype = model$model_name)) +
  
   # ------------ Group plot by participant -----------------
facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 4, scale = "free") + 
  # ------------ Change some axes settings  ----------------
#scale_y_continuous(limits=c(0, 3)) + 
  scale_x_continuous(name ="Response Error (degrees)", # also x axis name 
                     breaks = c(-2, 0, 2),
                     labels = c(expression(-pi), "0", expression(pi))) + 
  xlab("Response Error (degrees)") + # just in case remove scale x continuous 
  ylab("Response Time (s)") + 
  scale_color_manual(name = "Predicted \nQuantiles",
                     values = cols,  # cbPalette[c(1,2,3)], 
                     labels = c("0.1", "0.5", "0.9")) + 
  # ------------ Change Theme Settings  ----------------
ggtitle("Response Time Quantiles by Error") + 
  theme(
    
    # Legend settings 
    #legend.justification = c(1, 1), legend.position = c(0.90, 1.09),
    legend.background = element_blank(),
    
    # Axis settingd 
    axis.text.x = element_text(size=7),  # size of text on the x axis 
    axis.text.y = element_text(size=7),  # size of text on the y axis 
    
    # Plot title settings 
    plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
    plot.subtitle = element_text(hjust = 0.5), # subtitle settiings (note, centering requires h = 0.5)
    plot.caption = element_text(hjust = 0, face = "italic"), # caption settings 
    
    # Get rid of background panel grid 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black"))
  
  
  
```

```{r}
  
#   ggplot(data = model, 
#                    aes(x = model$theta, 
#                        y = model$rt, 
#                        group = model$quantile_idx,  # group points according to quantiles 
#                        colour = quantile_idx)) + 
#   geom_line(linemitre = 4) + #geom_point() + 
#   # ------------ Plot Data ---------------------------------
# # Plot data as POINTS ONLY
# geom_point(data = data, 
#            aes(x = data$theta, 
#                y = data$rt, 
#                group = data$quantile_idx, 
#                colour = quantile_idx)) + 
#   # ------------ Group plot by participant -----------------
# facet_wrap(~subjString, labeller = label_wrap_gen(width = 30), ncol = 4, scale = "free") + 
#   # ------------ Change some axes settings  ----------------
# #scale_y_continuous(limits=c(0, 3)) + 
#   scale_x_continuous(name ="Response Error (degrees)", # also x axis name 
#                      breaks = c(-2, 0, 2),
#                      labels = c(expression(-pi), "0", expression(pi))) + 
#   xlab("Response Error (degrees)") + # just in case remove scale x continuous 
#   ylab("Response Time (s)") + 
#   scale_color_manual(name = "Predicted \nQuantiles",
#                      values = cols,  # cbPalette[c(1,2,3)], 
#                      labels = c("0.1", "0.5", "0.9")) + 
#   # ------------ Change Theme Settings  ----------------
# ggtitle("Response Time Quantiles by Error") + 
#   theme(
#     
#     # Legend settings 
#     #legend.justification = c(1, 1), legend.position = c(0.90, 1.09),
#     legend.background = element_blank(),
#     
#     # Axis settingd 
#     axis.text.x = element_text(size=7),  # size of text on the x axis 
#     axis.text.y = element_text(size=7),  # size of text on the y axis 
#     
#     # Plot title settings 
#     plot.title = element_text(hjust = 0.5, size = 13),  # title settings (note, centering requires h = 0.5)
#     plot.subtitle = element_text(hjust = 0.5), # subtitle settiings (note, centering requires h = 0.5)
#     plot.caption = element_text(hjust = 0, face = "italic"), # caption settings 
#     
#     # Get rid of background panel grid 
#     panel.grid.major = element_blank(), 
#     panel.grid.minor = element_blank(),
#     panel.background = element_blank(), 
#     axis.line = element_line(colour = "black"))
# 
# QxQ # display the plot 
# 
# # Note: Device to use. Can be either be a device function (e.g. png()), 
# or one of "eps", "ps", "tex" (pictex), "pdf", "jpeg", "tiff", "png", 
# "bmp", "svg" or "wmf" (windows only).
# ggsave('pooled_QQ', plot = QxQ, device = "eps", path = NULL,
#        width = 20, height = 20, 
#        scale = 1, dpi = 800, limitsize = TRUE) # 

```


